---
- hosts: 192.168.1.143
  sudo: yes
  tasks:
   
   - copy:
      
        src: /home/sonal/mayank/ansible/cfg2html.rpm 
        dest: /tmp/cfg2html.rpm
        mode: 777
   - name: install cfg2html.rpm 
     yum: 
       name: /tmp/cfg2html.rpm 
       state: present



